Add missing fields to structs
buildkite/go-buildkite pull request #74
Opened 2020-09-24 20:56 UTC by kushmansingh

There fields specified in the API docs that are missing from this client lib, added them after verifying they existed via curl

2020-09-29 01:42 UTC, ticky requested changes
Looking great, I think there’s one change which would be helpful

2020-09-29 01:42 UTC, ticky commented on buildkite/pipelines.go
> +	Configuration                   string            `json:"configuration,omitempty" yaml:"configuration,omitempty"`
With YAML steps enabled, you supply either Steps or Configuration, so I believe these both need to be optional now:

```suggestion

	// Optional fields
	Steps                           []Step            `json:"steps,omitempty" yaml:"steps,omitempty"`
	Configuration                   string            `json:"configuration,omitempty" yaml:"configuration,omitempty"`
```

2020-09-29 01:42 UTC, ticky commented on buildkite/pipelines.go
> +	req, err := ps.client.NewRequest("PATCH", u, p)
I think this works, I’m not sure what properties that comment was talking about. 👍🏼

2020-10-08 22:42 UTC, sj26 commented
Neat!

Will this break if we add new fields to these responses?

2020-10-08 22:55 UTC, sj26 commented on buildkite/pipelines.go
> +	Steps         []Step `json:"steps" yaml:"steps"`
Should this be modified to `omitempty` as well?

2020-10-26 03:19 UTC, jayco commented on buildkite/pipelines.go
> +	Steps         []Step `json:"steps" yaml:"steps"`
```suggestion
	Steps         []Step `json:"steps, omitempty" yaml:"steps"`
```

2020-10-28 02:54 UTC, closed without merging

2020-10-28 03:05 UTC, JuanitoFatas commented
@kushmansingh Thanks Kush so much for your contributions ❤️  I will cut a release soon.