Support for Arching/Unarchiving pipelines
buildkite/go-buildkite pull request #85
Opened 2021-06-15 00:24 UTC by ksepehr

# Descriptions

Thanks to @shevaun for creating the REST API endpoints for us. We are already using the `archive/unarchive` endpoints she created via a forked `go-buildkite` and want to merge these back upstream now.

### Changes
* Added `Archive` method for `PipelinesService`.
* Added `Unarchive` method for `PipelinesService`.
* Exposing `ArchivedAt` field for `Pipeline` struct.

### Testing 
* Unit test for `Archive` and `Unarchive`
* Have tested this and was able to successfully archive, unarchive pipelines within our buildkite org. Also tested retrieving `ArchivedAt` field.

2021-06-15 03:32 UTC, ksepehr commented on buildkite/pipelines_test.go
> -		t.Errorf("Pipelines.Delete returned error: %v", err)
This is me fixing an error reporting from a previous test-case in a previous PR that I had made for adding AddWebhook support. Calling this out as it's unrelated to the rest of the PR.

2021-06-15 06:29 UTC, jayco requested changes

2021-06-15 06:29 UTC, jayco commented on buildkite/pipelines_test.go
> +		DefaultBranch: *String("main"),
```suggestion
		        DefaultBranch: *String("main"),
```

2021-06-15 06:32 UTC, jayco commented
This looks good @ksepehr, one small formatting change needed and I can merge.

2021-06-15 13:00 UTC, ksepehr commented on buildkite/pipelines_test.go
> +		DefaultBranch: *String("main"),
Good catch

2021-06-15 13:01 UTC, ksepehr commented
> This looks good @ksepehr, one small formatting change needed and I can merge.

Thank you, Updated.

2021-06-16 03:10 UTC, jayco reviewed
Looks good, thanks @ksepehr 🎉

2021-06-16 03:10 UTC, jayco approved these changes

2021-06-16 03:11 UTC, merged